EspEx.StreamName implementation
Carburetor/esp_ex pull request #1
Opened 2018-05-07 19:03 UTC by jerrysitu

2018-05-09 03:24 UTC, Fire-Dragon-DoL requested changes

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +  def new(category, identifier \\ nil, types \\ []) do
Mark this method with a guard-clause:

```elixir
def new(category, identifier \\ nil, types \\ []) when is_bitstring(category) do
```

You can entirely skip the `category == nil` check.
Also, the category you trim should be trimmed when you create the struct (otherwise it has whitespaces!). So:
`category = String.trim(category)` and just use that.

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +    result = Regex.run(~r/-(.+)/, string)
try to use better variable names. `identifier` rather than result makes more sense here.

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +    category = category_checker(string)
All 3 `_checker` are not checking anything and are actually _building a new string_.
Make sure to give those proper names, it can be extremely confusing for other developers, checker triggers the "returns a boolean" mind.

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +  defp types_checker(string) do
This one definitely needs refactoring. Make sure to have a function of ~5-7 lines at most (lean toward the 6, not the 7).

A lot of the problems come with the fact that you "ignore" work you have previously done in the other functions. You find the category, why don't you remove it from the string?

```elixir
category = extract_category(string)
name = String.trim_leading(string, category)
name = String.trim_leading(name, ":")
```

This converts `campaign:command+position-123` to `command+position-123`, much easier to extract types now!
Once you have types or the identifier, you can do the same. Let's say you extract the identifier:

```elixir
identifier = extract_identifier(name)
name = String.trim_trailing(name, identifier)
name = String.trim_trailing(name, "-")
```
And now `name` has only `command+position`, extracting the types is trivial. You probably don't need regex in most of the places!

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +      types = Enum.join(list, "+")
Add the `:` directly here. If it's empty, don't add anything, otherwise add `:`. You won't need to do anything else.

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +      identifier = map.identifier
You can create a helper function that converts identifier from `-#{identifier}` if it's not blank or nil. Otherwise, it just returns an empty string

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +      cond do
This condition is very complicated, while if you do the previous changes, you'll end up with just a string concatenation

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +    Enum.all?(list, fn x -> x in types end)
```elixir
map.types == :ordsets.from_list(list)
```

Replaces the whole function and it's probably more efficient.

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +  def is_category?(map) do
Rename `is_category?` to `category?`. Be aware that you can make this function a 2-liners:

```elixir
def category?(%__MODULE__{identifier: nil}), do: true
def category?(%__MODULE__{}), do: false
```

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on test/esp_ex/stream_name.exs
> -    test "raises with a blank string" do
Why did you remove this?

2018-05-09 03:24 UTC, Fire-Dragon-DoL commented on test/esp_ex/stream_name.exs
> +        assert struct.category == 123
You shouldn't assert inside an assert_raise

2018-05-10 21:09 UTC, jerrysitu commented on lib/esp_ex/stream_name.ex
> +  def new(category, identifier \\ nil, types \\ []) do
Should be better now.

2018-05-10 21:09 UTC, jerrysitu commented on lib/esp_ex/stream_name.ex
> +    result = Regex.run(~r/-(.+)/, string)
gotcha.

2018-05-10 21:09 UTC, jerrysitu commented on lib/esp_ex/stream_name.ex
> +    category = category_checker(string)
gotcha

2018-05-10 22:13 UTC, jerrysitu commented on lib/esp_ex/stream_name.ex
> +  defp types_checker(string) do
Ok, not as short as I wanted, but its shorter. than before.

2018-05-10 22:37 UTC, jerrysitu commented on test/esp_ex/stream_name.exs
> -    test "raises with a blank string" do
I can't remember, but its back in here now?.. at least on my side.. maybe i removed then put it back for some reason..

2018-05-10 23:14 UTC, jerrysitu commented on lib/esp_ex/stream_name.ex
> +    Enum.all?(list, fn x -> x in types end)
It has to be a direct match of both to work. 

It fails if its just looking for a subset

2018-05-10 23:25 UTC, jerrysitu commented on lib/esp_ex/stream_name.ex
> +  def is_category?(map) do
Ah pattern matching. right.

2018-05-10 23:25 UTC, jerrysitu commented on test/esp_ex/stream_name.exs
> +        assert struct.category == 123
fixed

2018-05-10 23:27 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +  alias StreamName
Not sure why you are aliasing it, but there is no need

2018-05-10 23:27 UTC, Fire-Dragon-DoL commented on lib/esp_ex/stream_name.ex
> +    types = map.types
Right, I forgot it has to be a subset:

```elixir
list
|> :ordsets.from_list()
|> :ordsets.is_subset(types)
```

2018-05-11 04:27 UTC, jerrysitu commented
I book the easy way out and created a new branch: https://github.com/Carburetor/esp_ex/pull/3

2018-05-11 04:28 UTC, closed without merging